language: ruby
rvm:
- 2.6.2

script:
  - bundle exec jekyll build
  - rake

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build