language: ruby
rvm:
- 2.4.2

script:
  - bundle exec jekyll build
  - rake

branches:
  only:
  - develop

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

after_success:
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - ./send.sh failure $WEBHOOK_URL