title: David Young
email: me@davidyoung.tech
description: > # this means to ignore newlines until "baseurl:"
  David Young is an Information Technology student based in Brisbane, Australia 
  with a keen interest in Website Development and Design majoring in Software 
  Development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.davidyoung.tech" # the base hostname & protocol for your site
twitter_username: dayvidwhy
github_username:  dayvidwhy

# Build settings
markdown: kramdown
