# build config
future: true
baseurl: "" # subpath, eg /blog
sass:
  style: compressed
strict_front_matter: true
plugins:
  - jekyll-feed
  - jekyll-sitemap

# global config
include: ['_pages']
exclude:
    - Rakefile
    - README.md

# serve config
open_url: true

# custom properties
title: David Young
email: hello@davidyoung.tech
description: "David Young is a developer with a keen interest in web development and design."
base_keywords: "developer, engineer, blog, david, young, david young"
url: "https://davidyoung.tech"
theme_colour: "#F4F2F0"
twitter: dayvidwhy
github:  dayvidwhy
