version: 2
jobs:
    build:
        docker:
            - image: circleci/ruby:2.4.2-node-browsers
        steps:
            - checkout
            - run: bundle install
            - run: bundle exec jekyll build
    test:
        docker:
            - image: circleci/ruby:2.4.2-node-browsers
        steps:
            - run: rake
workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - test